name: Sync on DOM Cloud

'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"commands":[
              "cd public_html",
              "git pull",
              "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader",
              "php artisan migrate --force",
              "php artisan config:cache",
              "php artisan route:cache || true",
              "php artisan view:cache || true",
              "php artisan event:cache || true",
              "npm ci || npm install",
              "npm run build",
              "php artisan storage:link || true",
              "rm -f public/hot || true",
              "chmod 0750 -R storage bootstrap/cache || true",
              "restart"
            ]}
